name: Docker Image CI

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

env:
  DOCKER_HUB_ORG: ${{ secrets.DOCKERHUB_ORG }}
  DOCKER_IMAGE_NAME: squid3
  DOCKER_IMAGE_TAG: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.sha }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    # Build the Docker image
    - name: Build with Docker
      run: |
        cp configFiles/squid.conf docker && cp configFiles/squid_passwd docker
        docker build -t "$DOCKER_HUB_ORG"/"$DOCKER_IMAGE_NAME":"$DOCKER_IMAGE_TAG" docker

    # Push the image to IBM Container Registry
    - name: Push the image to DockerHub
      run: |
        docker push "$DOCKER_HUB_ORG"/"$DOCKER_IMAGE_NAME":"$DOCKER_IMAGE_TAG"

    - name: CF CLI Action
      # You may pin to the exact commit or the version.
      # uses: citizen-of-planet-earth/cf-cli-action@3c7cc1a77152f9157b0c33b32d3b2b5fbdc56dca
      uses: citizen-of-planet-earth/cf-cli-action@v2
      with:
        # Target API Endpoint of Cloud Foundry
        cf_api: https://api.us-south.cf.cloud.ibm.com
        # Username for API authentication
        cf_username: apikey
        # Password for API authentication
        cf_password: ${{ secrets.CF_API_KEY }}
        # Target Organization
        cf_org: ${{ secrets.CF_ORG }}
        # Target Space
        cf_space: dev
        # Command to run using CF CLI
        command: push myappinqq -o "$DOCKER_HUB_ORG"/"$DOCKER_IMAGE_NAME":"$DOCKER_IMAGE_TAG" -m 256M
